language: generic
dist: xenial
addons:
  apt:
    packages:
      - make
      - latexmk
      - texlive
      - texlive-lang-portuguese
      - texlive-latex-extra
      - texlive-publishers
      - texlive-science
      - texlive-xetex
      - ghostscript
script:
  - make help
  - make clean
  - make compile-test
  - make compress
