name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up git repository
        uses: actions/checkout@v2.4.0

      - name: Install dependencies
        run: |
          sudo apt-get -y install \
            make \
            latexmk \
            texlive \
            texlive-lang-portuguese \
            texlive-latex-extra \
            texlive-publishers \
            texlive-science \
            texlive-xetex

      - name: Build latex project
        run: make

      - name: Clean latex project
        run: make clean
