name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up git repository
        uses: actions/checkout@v2.4.0

      - name: Install dependencies
        run: |
          sudo apt -y install make
          sudo apt -y install latexmk
          sudo apt -y install texlive
          sudo apt -y install texlive-lang-portuguese
          sudo apt -y install texlive-latex-extra
          sudo apt -y install texlive-publishers
          sudo apt -y install texlive-science
          sudo apt -y install texlive-xetex

      - name: Build latex project
        run: make

      - name: Clean latex project
        run: make clean
